Fixed RDKit build error
Fixed compiler error:
RDLog.h:131:8: error: 'uint64_t' in namespace 'std' does not name a type

This is caused by a missing '#include <cstdint>' in RDLog.h.

This has been fixed in RDKit https://github.com/rdkit/rdkit/commit/f4e929a440d0fffe57be63f20cb0088763ef4c62
so when we update to RDKit 2023_03_2 this patch may be removed.